# Generated by Django 4.2.5 on 2023-09-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_info_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static\\img'),
        ),
        migrations.AddField(
            model_name='info',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
